---
.static_template: &static_template
  before_script:
    - composer install
    - ./vendor/govcms/scaffold-tooling/gitlab/setup-static.sh
  stage: static

.full_template: &full_template
  before_script:
    - composer install
    - ./vendor/govcms/scaffold-tooling/gitlab/setup-full.sh
  artifacts:
    expire_in: "7 days"
    paths:
      - tests/behat/features/screenshots
  stage: integration

image: quay.io/tobybellwood/govcms-ci
services:
  - "docker:dind"
stages:
  - static
  - integration
  - audit
  - deploy
variables:
  extends: .variables
  DOCKER_HOST: "tcp://localhost:2375"

vet:
  <<: *static_template
  script:
    - echo "We'll run verification here"
static:
  <<: *static_template
  extends: .static
  script: |
    set +euo pipefail # Make sure all scripts run (an error in any is still a gitlab job fail).
    ./vendor/bin/govcms-lint web/modules/custom
    ./vendor/bin/govcms-lint web/themes/custom
    ./vendor/bin/govcms-phpunit web/modules/custom
  stage: static
functional:
  <<: *full_template
  extends: .func
  script:
    - docker-compose exec -T test behat
  except:
    variables:
      - "$CI_COMMIT_MESSAGE =~ /GovCMS-Migration/"
audit:
  <<: *full_template
  script:
    - docker-compose exec -T test audit
  only:
    - merge_requests
  stage: audit
audit_manual:
  <<: *full_template
  script:
    - docker-compose exec -T test audit
  when: manual
  stage: audit
deploy:
  script:
    - "echo \"curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy\""
    - "curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy"
  stage: deploy
