---
.static_template: &static_template
  before_script:
    - composer install --quiet
  stage: static

.full_template: &full_template
  before_script:
    - composer install --quiet
    - ./vendor/govcms/scaffold-tooling/gitlab/setup-full.sh
  artifacts:
    expire_in: "7 days"
    paths:
      - tests/behat/features/screenshots
  stage: integration

image: quay.io/tobybellwood/govcms-ci
services:
  - "docker:dind"
stages:
  - static
  - integration
  - audit
  - deploy
variables:
  extends: .variables
  DOCKER_HOST: "tcp://localhost:2375"

vet:
  <<: *static_template
  script:
    - echo "We'll run verification here"
static:
  <<: *static_template
  extends: .static-tests
  script: |
    set +euo pipefail # Make sure all scripts run (an error in any is still a gitlab job fail).
    ./vendor/bin/govcms-lint web/modules/custom
    ./vendor/bin/govcms-lint web/themes/custom
    # @todo this needs to run only static phpunit tests - no integration tests as Drupal can't be bootstrapped.
    # ./vendor/bin/govcms-phpunit --testsuite=unit
  stage: static
functional:
  <<: *full_template
  extends: .integration-tests
  script:
    - docker-compose exec -T test ./vendor/bin/govcms-behat
audit:
  <<: *full_template
  script:
    - docker-compose exec -T test ./vendor/bin/govcms-audit
  only:
    - merge_requests
  stage: audit
audit_manual:
  <<: *full_template
  script:
    - docker-compose exec -T test ./vendor/bin/govcms-audit
  when: manual
  stage: audit
deploy:
  script:
    - "echo \"curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy\""
    - "curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy"
  stage: deploy
