---
.static_template: &static_template
  before_script:
    - wget -O - https://raw.githubusercontent.com/simesy/scaffold-tooling/49bd0cd/gitlab/setup-minimal.sh | bash
  stage: static

.bootstrap_template: &bootstrap_template
  before_script:
    - wget -O - https://raw.githubusercontent.com/simesy/scaffold-tooling/fa5395d/gitlab/setup-smoketests.sh | bash
  stage: static

.full_template: &full_template
  before_script:
    - wget -O - https://raw.githubusercontent.com/simesy/scaffold-tooling/fa5395d/gitlab/setup-full.sh | bash
  artifacts:
    expire_in: "7 days"
    paths:
      - tests/behat/features/screenshots
  stage: integration

image: quay.io/tobybellwood/govcms-ci
services:
  - "docker:dind"
stages:
  - static
  - preflight
  - integration
  - deploy
variables:
  extends: .variables
  DOCKER_HOST: "tcp://localhost:2375"
# @todo see GOVCMS-3110
#cache:
#  key: "$CI_PROJECT_PATH_SLUG"
#  paths:
#    - /home/.composer/cache

# Static.

vet:
  script:
    - composer validate
  when: on_success
  allow_failure: false
  stage: static

lint:
  <<: *static_template
  extends: .job-lint
  # Run all lines together so that they all run even if any fail.
  script: |
    set +exuo pipefail # Linting...
    docker-compose exec -T test bash -c '/app/vendor/bin/govcms-lint web/modules/custom'
    docker-compose exec -T test bash -c '/app/vendor/bin/govcms-lint web/themes/custom'
unit:
  <<: *static_template
  extends: .job-unit
  script:
    - docker-compose exec -T test bash -c './vendor/bin/govcms-unit --testsuite=unit'

# Pre-flight.

preflight:
  <<: *bootstrap_template
  extends: .job-preflight
  stage: preflight
  script:
    - docker-compose exec -T cli bash -c 'drush cim -y'
    - docker-compose exec -T cli bash -c 'drush st'
    - docker-compose exec -T cli bash -c 'drush updatedb:status'

# Integration.
behat:
  <<: *full_template
  extends: .job-behat
  script:
    - docker-compose exec -T test ./vendor/bin/govcms-behat
functional:
  <<: *full_template
  extends: .job-functional
  script:
    - echo "Will run something like docker-compose exec -T test ./vendor/bin/govcms-integration"
audit:
  <<: *full_template
  extends: .job-audit
  script:
    - docker-compose exec -T test ./vendor/bin/govcms-audit

# MRs only.
audit_on_merge:
  <<: *full_template
  extends: .job-audit-on-merge
  script:
    - docker-compose exec -T test ./vendor/bin/govcms-audit
  only:
    - merge_requests
  stage: deploy

# Deploy / summary.
deploy:
  variables:
    GOVCMS_DASHBOARD: "https://dashboard.govcms.gov.au/projects"
  script:
    - echo "Deployment triggered, please see $GOVCMS_DASHBOARD/$CI_PROJECT_NAME/$CI_PROJECT_NAME-$(echo $CI_COMMIT_REF_NAME | sed -e 's/[^[:alnum:]-]/-/g')"
  stage: deploy
