# This is poc rework of https://projects.govcms.gov.au/GovCMS/govcms8-scaffold-ci/raw/master/.gitlab-ci-include.yml
---
image: govcmsdev/gitlab-ci
services:
  - "docker:dind"
stages:
  - static
  - integration
  - deploy
before_script:
  - "export DOCKER_HOST=tcp://localhost:2375"
  - "docker network prune -f && docker network create amazeeio-network"
  - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry-production.govcms.amazee.io"
static:
  script:
    - "docker-compose up -d test"
    # - vet
    - "ahoy lint || true"
    - "ahoy test-phpunit"
  stage: test
functional:
  artifacts:
    expire_in: "7 days"
    paths:
      - tests/behat/features/screenshots
  except:
    variables:
      - "$CI_COMMIT_MESSAGE =~ /GovCMS-Migration/"
  script:
    - "docker-compose up -d"
    - "docker-compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 1m"
    - |
      if grep --quiet '^MARIADB_DATA_IMAGE' .env; then
        ahoy govcms-deploy
      else
        ahoy -v install -- install_configure_form.update_status_module='array(FALSE,FALSE)'
      fi
    - "ahoy test-behat"
    # - "ahoy audit-site"
    - date
  stage: functional
deploy:
  script:
    - "echo \"curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy\""
    - "curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks.lagoon.svc:3000/deploy"
  stage: deploy
